ProjetCrawling/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jeuxvideo/', include('jeuxvideo.urls')),
    url(r'^film/', include('film.urls')),
]

film/urls.py
from django.conf.urls import url, include
from . import views
from .views import FilmListView

app_name = 'film'
urlpatterns = [
    url(r'^listefilm/', FilmListView.as_view(), name='film-liste'),
    ]

jeuxvideo/urls.py
from django.conf.urls import url, include
from . import views
from .views import JeuxListView, search, result_search

app_name = 'jeuxvideo'
urlpatterns = [
    url(r'^home/(\w+)?', views.home, name='home'),
    url(r'^listejeux/', JeuxListView.as_view(), name='jeux-liste'),
    url(r'^search/', search, name='search'),
    url(r'^result/(\w+)?', result_search, name='result'),
    ]

film/models.py
from django.db import models


class Film(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=230)
    sortie = models.CharField(max_length=230)
    AnneeSortie = models.CharField(max_length=4)

def __str__(self):
    return '{self.name}'

jeuxvideo/models.py
from django.db import models
from igdb_api_python.igdb import igdb

class Jeux(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=64)
    cover = models.CharField(max_length=64)
    first_release_date = models.IntegerField()
        
    def __str__(self):
        return '{self.name}'

film/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import DetailView, ListView
from .models import Film


def film_detail(request,pk):
    return HttpResponse('OK')


class FilmListView(ListView):
    model = Film
    template_name = 'film/test.html'

jeuxvideo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import DetailView, ListView
from igdb_api_python.igdb import igdb

def home(request,name):
    return render(request, 'jeuxvideo/accueil.html')

def search(request):
    return render(request, 'jeuxvideo/search.html')

def get_key():
    return igdb("b34ee13a58748558d9f273c965c65a7f")

def result_search(request, args):
    igbd = igdb("b34ee13a58748558d9f273c965c65a7f")
    result = igdb.games({
        'search': request.GET['name'],
        'fields': ['name','cover','first_release_date']
    })
    return result.body

from django.views.generic import DetailView
from .models import Jeux

class JeuxListView(ListView):
    model = Jeux
    template_name = 'jeuxvideo/test.html'

film/templates/film/test.html
{% extends "jeuxvideo/base.html" %}
{% block contenu %}
    <div class="list-group">
      {% for Film in object_list %}
      <a class="list-group-item list-group-item-action list-group-item-info flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{Film.name}}</h5>
        </div>
        <p class="mb-1">{{Film.sortie}}</p>

      </a>
      {% endfor %}
    </div>

{% endblock %}

jeuxvideo/templates/jeuxvideo/accueil.html
{% extends "jeuxvideo/base.html" %}
{% block contenu %}
    <p><a href="{% url 'jeuxvideo:search' %}" class="top-menu">Rechercher un jeu</a></p>
    <p><a href="{% url 'jeuxvideo:jeux-liste' %}" class="top-menu">Liste des jeux</a></p>
    <p><a href="{% url 'film:film-liste' %}" class="top-menu">Liste des films</a></p>
{% endblock %}

jeuxvideo/templates/jeuxvideo/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'images/igbd_logo.png' %}" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/jeuxvideo.css' %}">
    <title>Portail Univers JV</title>
</head>
<body>
    <div class="row">
        <div class="col-md-1">
            <a href="{% url 'jeuxvideo:home' %}">
            <img src = "{% static 'images/igbd_logo.png' %}" alt="Logo">
        </div>
        <div class="col-md-7">
            <h1>Portail Univers JV</h1>
            </a>
            <hr>
        </div>
        <nav class="content container">
            <div class="col-md-6">
                {% block contenu %}
                {% endblock %}
            </div>
        </nav>
    </div>
</body>
</html>

jeuxvideo/templates/jeuxvideo/search.html
{% extends "jeuxvideo/base.html" %}
{% block contenu %}
    <form action="{% url 'jeuxvideo:result' %}" method="get">
        <p>Nom du jeu : <input type="text" name="name" id="name"></p>
        <input type="submit" value="Submit">
    </form> 
{% endblock %}

jeuxvideo/templates/jeuxvideo/test.html
{% extends "jeuxvideo/base.html" %}
{% block contenu %}
    <p>{{Jeux.name}}</p>
    <p><img src="{{Jeux.screen}}" alt="Image non trouvée"></p>
{% endblock %}